name: VectorDB Sync

on:
  pull_request:
    types: [closed]

jobs:
  sync:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || true  # won't fail if no requirements

      - name: Detect changed files (root + submodules)
        run: |
          echo "🔎 Detecting main repo file changes..."
          git diff --name-status origin/main HEAD > changed_files.txt || true
          cat changed_files.txt

          echo "🔎 Detecting submodule pointer changes..."
          git diff --submodule > submodule_changes.txt || true
          cat submodule_changes.txt

          echo "🔎 Expanding submodule changes into file-level diffs..."
          while read -r line; do
            submodule=$(echo "$line" | awk '{print $1}')
            oldsha=$(echo "$line" | awk '{print $2}')
            newsha=$(echo "$line" | awk '{print $3}')
            if [ -n "$submodule" ] && [ -n "$oldsha" ] && [ -n "$newsha" ]; then
              echo "📂 Submodule: $submodule ($oldsha → $newsha)"
              pushd $submodule > /dev/null
              git fetch origin $oldsha $newsha || true
              git diff --name-status $oldsha $newsha | sed "s|^|$submodule/|" >> ../changed_files.txt
              popd > /dev/null
            fi
          done < <(git diff --submodule | grep Submodule)

          echo "✅ Final changed files list:"
          cat changed_files.txt
